### ISSUE TITLE
Please add iOS and Mac support back

### ISSUE THREAD

**Issue by tidusjar** [MattJeanes/ThermalCamera#1]
I noticed we removed iOS and Mac Support, please add this back, this is mission-critical. I'm trying to keep the food on my employee's tables here.

**Comment by sophia-ma** [comment]
+1

What about the people who don't have windows PC? I don't understand why someone would remove the support for Macs...

**Comment by AmyJeanes** [comment]
Buy me a Mac so I can compile for it and I will consider your request

**Comment by tidusjar** [comment]
My employees are not going to be able to eat now. Hope you can live with that.

**Comment by AmyJeanes** [comment]
@tidusjar emotional blackmail won't work on me, I'm used to it
